CREATE TABLE budget (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    amount INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- default to current time
)
